version: 2.1

jobs:
  pingpong:
    machine: true
    resource_class: kelvintaywl-cci/ec2-linux2023-tf
    steps:
      - checkout
      - run: echo "Forked: biteupco/server4-machine-runner-inspect"

workflows:
  main:
    jobs:
      - pingpong
